### ISSUE TITLE
“你怎么还在看电脑？”

### ISSUE THREAD

**Issue by Cursor-S** [WORKXR/WORKX#1]
“什么管理作业，我现在看到你开电脑我就心慌。光想做计划有什么用啊去落实啊盯着屏幕写计划有个p用现在给我关机”

**Comment by WUTONK** [comment]
草草草草草
(但是我们是IOS端的哦)

**Comment by Cursor-S** [comment]
我 iphone 因为我看太多被我妈咔嚓了（

**Comment by Qubik65536** [comment]
Closed and locked due to off-topic discussion
